[2022-05-29 14:52:09,939] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: Gamer_Daily_Request.get_lottery manual__2022-05-29T06:51:55.517891+00:00 [queued]>
[2022-05-29 14:52:09,947] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: Gamer_Daily_Request.get_lottery manual__2022-05-29T06:51:55.517891+00:00 [queued]>
[2022-05-29 14:52:09,947] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-29 14:52:09,947] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-29 14:52:09,948] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-29 14:52:09,960] {taskinstance.py:1378} INFO - Executing <Task(_PythonDecoratedOperator): get_lottery> on 2022-05-29 06:51:55.517891+00:00
[2022-05-29 14:52:09,963] {standard_task_runner.py:52} INFO - Started process 50748 to run task
[2022-05-29 14:52:09,971] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Gamer_Daily_Request', 'get_lottery', 'manual__2022-05-29T06:51:55.517891+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/gamer_dag.py', '--cfg-path', '/var/folders/7p/8y53sxp17879s6k6nzygbwgw0000gn/T/tmp4_53ecob', '--error-file', '/var/folders/7p/8y53sxp17879s6k6nzygbwgw0000gn/T/tmparxot7pk']
[2022-05-29 14:52:09,974] {standard_task_runner.py:80} INFO - Job 127: Subtask get_lottery
[2022-05-29 14:52:10,034] {task_command.py:370} INFO - Running <TaskInstance: Gamer_Daily_Request.get_lottery manual__2022-05-29T06:51:55.517891+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-05-29 14:52:10,101] {taskinstance.py:1570} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=b01201008@gmail.com
AIRFLOW_CTX_DAG_OWNER=randy
AIRFLOW_CTX_DAG_ID=Gamer_Daily_Request
AIRFLOW_CTX_TASK_ID=get_lottery
AIRFLOW_CTX_EXECUTION_DATE=2022-05-29T06:51:55.517891+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-29T06:51:55.517891+00:00
[2022-05-29 14:52:53,639] {logging_mixin.py:115} INFO - Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.close_button"}
  (Session info: chrome=102.0.5005.61)
Stacktrace:
0   chromedriver                        0x00000001064c0d19 chromedriver + 5197081
1   chromedriver                        0x000000010644eb23 chromedriver + 4729635
2   chromedriver                        0x000000010602c2b8 chromedriver + 393912
3   chromedriver                        0x00000001060612fd chromedriver + 611069
4   chromedriver                        0x0000000106061581 chromedriver + 611713
5   chromedriver                        0x00000001060935a4 chromedriver + 816548
6   chromedriver                        0x000000010607e82d chromedriver + 731181
7   chromedriver                        0x00000001060912a1 chromedriver + 807585
8   chromedriver                        0x000000010607e6f3 chromedriver + 730867
9   chromedriver                        0x0000000106054a49 chromedriver + 559689
10  chromedriver                        0x0000000106055a75 chromedriver + 563829
11  chromedriver                        0x0000000106492bdd chromedriver + 5008349
12  chromedriver                        0x0000000106497b64 chromedriver + 5028708
13  chromedriver                        0x000000010649cbcf chromedriver + 5049295
14  chromedriver                        0x00000001064987ca chromedriver + 5031882
15  chromedriver                        0x000000010647259f chromedriver + 4875679
16  chromedriver                        0x00000001064b2388 chromedriver + 5137288
17  chromedriver                        0x00000001064b250f chromedriver + 5137679
18  chromedriver                        0x00000001064c8085 chromedriver + 5226629
19  libsystem_pthread.dylib             0x00007ff819e344e1 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff819e2ff6b thread_start + 15
[2022-05-29 14:52:53,639] {logging_mixin.py:115} INFO - fail to click div.close_button
[2022-05-29 14:53:07,583] {logging_mixin.py:115} INFO - Message: no such element: Unable to locate element: {"method":"css selector","selector":"div[class*='rewardDialogueWrapper']:not([style*='display']) div.rewardResumebutton"}
  (Session info: chrome=102.0.5005.61)
Stacktrace:
0   chromedriver                        0x00000001064c0d19 chromedriver + 5197081
1   chromedriver                        0x000000010644eb23 chromedriver + 4729635
2   chromedriver                        0x000000010602c2b8 chromedriver + 393912
3   chromedriver                        0x00000001060612fd chromedriver + 611069
4   chromedriver                        0x0000000106061581 chromedriver + 611713
5   chromedriver                        0x00000001060935a4 chromedriver + 816548
6   chromedriver                        0x000000010607e82d chromedriver + 731181
7   chromedriver                        0x00000001060912a1 chromedriver + 807585
8   chromedriver                        0x000000010607e6f3 chromedriver + 730867
9   chromedriver                        0x0000000106054a49 chromedriver + 559689
10  chromedriver                        0x0000000106055a75 chromedriver + 563829
11  chromedriver                        0x0000000106492bdd chromedriver + 5008349
12  chromedriver                        0x0000000106497b64 chromedriver + 5028708
13  chromedriver                        0x000000010649cbcf chromedriver + 5049295
14  chromedriver                        0x00000001064987ca chromedriver + 5031882
15  chromedriver                        0x000000010647259f chromedriver + 4875679
16  chromedriver                        0x00000001064b2388 chromedriver + 5137288
17  chromedriver                        0x00000001064b250f chromedriver + 5137679
18  chromedriver                        0x00000001064c8085 chromedriver + 5226629
19  libsystem_pthread.dylib             0x00007ff819e344e1 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff819e2ff6b thread_start + 15
[2022-05-29 14:53:07,583] {logging_mixin.py:115} INFO - fail to click div[class*='rewardDialogueWrapper']:not([style*='display']) div.rewardResumebutton
[2022-05-29 14:53:37,597] {logging_mixin.py:115} INFO - Message: no such element: Unable to locate element: {"method":"css selector","selector":"img[src*='close-circle']"}
  (Session info: chrome=102.0.5005.61)
Stacktrace:
0   chromedriver                        0x00000001064c0d19 chromedriver + 5197081
1   chromedriver                        0x000000010644eb23 chromedriver + 4729635
2   chromedriver                        0x000000010602c2b8 chromedriver + 393912
3   chromedriver                        0x00000001060612fd chromedriver + 611069
4   chromedriver                        0x0000000106061581 chromedriver + 611713
5   chromedriver                        0x00000001060935a4 chromedriver + 816548
6   chromedriver                        0x000000010607e82d chromedriver + 731181
7   chromedriver                        0x00000001060912a1 chromedriver + 807585
8   chromedriver                        0x000000010607e6f3 chromedriver + 730867
9   chromedriver                        0x0000000106054a49 chromedriver + 559689
10  chromedriver                        0x0000000106055a75 chromedriver + 563829
11  chromedriver                        0x0000000106492bdd chromedriver + 5008349
12  chromedriver                        0x0000000106497b64 chromedriver + 5028708
13  chromedriver                        0x000000010649cbcf chromedriver + 5049295
14  chromedriver                        0x00000001064987ca chromedriver + 5031882
15  chromedriver                        0x000000010647259f chromedriver + 4875679
16  chromedriver                        0x00000001064b2388 chromedriver + 5137288
17  chromedriver                        0x00000001064b250f chromedriver + 5137679
18  chromedriver                        0x00000001064c8085 chromedriver + 5226629
19  libsystem_pthread.dylib             0x00007ff819e344e1 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff819e2ff6b thread_start + 15
[2022-05-29 14:53:37,598] {logging_mixin.py:115} INFO - fail to click img[src*='close-circle']
[2022-05-29 14:53:37,607] {logging_mixin.py:115} INFO - Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.close_button"}
  (Session info: chrome=102.0.5005.61)
Stacktrace:
0   chromedriver                        0x00000001064c0d19 chromedriver + 5197081
1   chromedriver                        0x000000010644eb23 chromedriver + 4729635
2   chromedriver                        0x000000010602c2b8 chromedriver + 393912
3   chromedriver                        0x00000001060612fd chromedriver + 611069
4   chromedriver                        0x0000000106061581 chromedriver + 611713
5   chromedriver                        0x00000001060935a4 chromedriver + 816548
6   chromedriver                        0x000000010607e82d chromedriver + 731181
7   chromedriver                        0x00000001060912a1 chromedriver + 807585
8   chromedriver                        0x000000010607e6f3 chromedriver + 730867
9   chromedriver                        0x0000000106054a49 chromedriver + 559689
10  chromedriver                        0x0000000106055a75 chromedriver + 563829
11  chromedriver                        0x0000000106492bdd chromedriver + 5008349
12  chromedriver                        0x0000000106497b64 chromedriver + 5028708
13  chromedriver                        0x000000010649cbcf chromedriver + 5049295
14  chromedriver                        0x00000001064987ca chromedriver + 5031882
15  chromedriver                        0x000000010647259f chromedriver + 4875679
16  chromedriver                        0x00000001064b2388 chromedriver + 5137288
17  chromedriver                        0x00000001064b250f chromedriver + 5137679
18  chromedriver                        0x00000001064c8085 chromedriver + 5226629
19  libsystem_pthread.dylib             0x00007ff819e344e1 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff819e2ff6b thread_start + 15
[2022-05-29 14:53:37,607] {logging_mixin.py:115} INFO - fail to click div.close_button
[2022-05-29 14:53:39,621] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/user/flow-for-randy/dags/gamer_dag.py", line 27, in get_lottery
  File "/Users/user/flow-for-randy/dags/services/gamer.py", line 92, in get_lotteries
    self.get_lottery(lottery_page)
  File "/Users/user/flow-for-randy/dags/services/gamer.py", line 58, in wrap
    return func(self, *args, **kwargs)
  File "/Users/user/flow-for-randy/dags/services/gamer.py", line 85, in get_lottery
    self.browser.click(GamerElement.lottery_confirm_radio)
  File "/Users/user/flow-for-randy/dags/services/drivers/selenium_driver.py", line 28, in click
    self.find_element(el).click()
  File "/Users/user/flow-for-randy/dags/services/drivers/selenium_driver.py", line 22, in find_element
    return self.driver.find_element(By.CSS_SELECTOR, el.value)
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 1251, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"input#agree-confirm"}
  (Session info: chrome=102.0.5005.61)
Stacktrace:
0   chromedriver                        0x00000001064c0d19 chromedriver + 5197081
1   chromedriver                        0x000000010644eb23 chromedriver + 4729635
2   chromedriver                        0x000000010602c2b8 chromedriver + 393912
3   chromedriver                        0x00000001060612fd chromedriver + 611069
4   chromedriver                        0x0000000106061581 chromedriver + 611713
5   chromedriver                        0x00000001060935a4 chromedriver + 816548
6   chromedriver                        0x000000010607e82d chromedriver + 731181
7   chromedriver                        0x00000001060912a1 chromedriver + 807585
8   chromedriver                        0x000000010607e6f3 chromedriver + 730867
9   chromedriver                        0x0000000106054a49 chromedriver + 559689
10  chromedriver                        0x0000000106055a75 chromedriver + 563829
11  chromedriver                        0x0000000106492bdd chromedriver + 5008349
12  chromedriver                        0x0000000106497b64 chromedriver + 5028708
13  chromedriver                        0x000000010649cbcf chromedriver + 5049295
14  chromedriver                        0x00000001064987ca chromedriver + 5031882
15  chromedriver                        0x000000010647259f chromedriver + 4875679
16  chromedriver                        0x00000001064b2388 chromedriver + 5137288
17  chromedriver                        0x00000001064b250f chromedriver + 5137679
18  chromedriver                        0x00000001064c8085 chromedriver + 5226629
19  libsystem_pthread.dylib             0x00007ff819e344e1 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff819e2ff6b thread_start + 15

[2022-05-29 14:53:39,633] {taskinstance.py:1396} INFO - Marking task as FAILED. dag_id=Gamer_Daily_Request, task_id=get_lottery, execution_date=20220529T065155, start_date=20220529T065209, end_date=20220529T065339
[2022-05-29 14:53:39,658] {logging_mixin.py:115} WARNING - /Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/airflow/utils/email.py:119 PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2022-05-29 14:53:39,658] {configuration.py:549} WARNING - section/key [smtp/smtp_user] not found in config
[2022-05-29 14:53:39,659] {email.py:228} INFO - Email alerting: attempt 1
[2022-05-29 14:53:39,663] {configuration.py:549} WARNING - section/key [smtp/smtp_user] not found in config
[2022-05-29 14:53:39,663] {email.py:228} INFO - Email alerting: attempt 1
[2022-05-29 14:53:39,664] {taskinstance.py:1945} ERROR - Failed to send email to: ['b01201008@gmail.com']
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1452, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1599, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1660, in _execute_task
    result = execute_callable(context=context)
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/user/flow-for-randy/dags/gamer_dag.py", line 27, in get_lottery
  File "/Users/user/flow-for-randy/dags/services/gamer.py", line 92, in get_lotteries
    self.get_lottery(lottery_page)
  File "/Users/user/flow-for-randy/dags/services/gamer.py", line 58, in wrap
    return func(self, *args, **kwargs)
  File "/Users/user/flow-for-randy/dags/services/gamer.py", line 85, in get_lottery
    self.browser.click(GamerElement.lottery_confirm_radio)
  File "/Users/user/flow-for-randy/dags/services/drivers/selenium_driver.py", line 28, in click
    self.find_element(el).click()
  File "/Users/user/flow-for-randy/dags/services/drivers/selenium_driver.py", line 22, in find_element
    return self.driver.find_element(By.CSS_SELECTOR, el.value)
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 1251, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"input#agree-confirm"}
  (Session info: chrome=102.0.5005.61)
Stacktrace:
0   chromedriver                        0x00000001064c0d19 chromedriver + 5197081
1   chromedriver                        0x000000010644eb23 chromedriver + 4729635
2   chromedriver                        0x000000010602c2b8 chromedriver + 393912
3   chromedriver                        0x00000001060612fd chromedriver + 611069
4   chromedriver                        0x0000000106061581 chromedriver + 611713
5   chromedriver                        0x00000001060935a4 chromedriver + 816548
6   chromedriver                        0x000000010607e82d chromedriver + 731181
7   chromedriver                        0x00000001060912a1 chromedriver + 807585
8   chromedriver                        0x000000010607e6f3 chromedriver + 730867
9   chromedriver                        0x0000000106054a49 chromedriver + 559689
10  chromedriver                        0x0000000106055a75 chromedriver + 563829
11  chromedriver                        0x0000000106492bdd chromedriver + 5008349
12  chromedriver                        0x0000000106497b64 chromedriver + 5028708
13  chromedriver                        0x000000010649cbcf chromedriver + 5049295
14  chromedriver                        0x00000001064987ca chromedriver + 5031882
15  chromedriver                        0x000000010647259f chromedriver + 4875679
16  chromedriver                        0x00000001064b2388 chromedriver + 5137288
17  chromedriver                        0x00000001064b250f chromedriver + 5137679
18  chromedriver                        0x00000001064c8085 chromedriver + 5226629
19  libsystem_pthread.dylib             0x00007ff819e344e1 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff819e2ff6b thread_start + 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2329, in email_alert
    send_email(task.email, subject, html_content)
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/airflow/utils/email.py", line 58, in send_email
    return backend(
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/airflow/utils/email.py", line 119, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/airflow/utils/email.py", line 230, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/airflow/utils/email.py", line 264, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1943, in handle_failure
    self.email_alert(error, task)
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2331, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/airflow/utils/email.py", line 58, in send_email
    return backend(
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/airflow/utils/email.py", line 119, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/airflow/utils/email.py", line 230, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/site-packages/airflow/utils/email.py", line 264, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/Users/user/.pyenv/versions/3.8.13/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused
[2022-05-29 14:53:39,677] {standard_task_runner.py:92} ERROR - Failed to execute job 127 for task get_lottery (Message: no such element: Unable to locate element: {"method":"css selector","selector":"input#agree-confirm"}
  (Session info: chrome=102.0.5005.61)
Stacktrace:
0   chromedriver                        0x00000001064c0d19 chromedriver + 5197081
1   chromedriver                        0x000000010644eb23 chromedriver + 4729635
2   chromedriver                        0x000000010602c2b8 chromedriver + 393912
3   chromedriver                        0x00000001060612fd chromedriver + 611069
4   chromedriver                        0x0000000106061581 chromedriver + 611713
5   chromedriver                        0x00000001060935a4 chromedriver + 816548
6   chromedriver                        0x000000010607e82d chromedriver + 731181
7   chromedriver                        0x00000001060912a1 chromedriver + 807585
8   chromedriver                        0x000000010607e6f3 chromedriver + 730867
9   chromedriver                        0x0000000106054a49 chromedriver + 559689
10  chromedriver                        0x0000000106055a75 chromedriver + 563829
11  chromedriver                        0x0000000106492bdd chromedriver + 5008349
12  chromedriver                        0x0000000106497b64 chromedriver + 5028708
13  chromedriver                        0x000000010649cbcf chromedriver + 5049295
14  chromedriver                        0x00000001064987ca chromedriver + 5031882
15  chromedriver                        0x000000010647259f chromedriver + 4875679
16  chromedriver                        0x00000001064b2388 chromedriver + 5137288
17  chromedriver                        0x00000001064b250f chromedriver + 5137679
18  chromedriver                        0x00000001064c8085 chromedriver + 5226629
19  libsystem_pthread.dylib             0x00007ff819e344e1 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff819e2ff6b thread_start + 15
; 50748)
[2022-05-29 14:53:39,696] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-29 14:53:39,719] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
